import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    'home',
    {
      type: 'category',
      label: 'Guides pour comprendre le MDN',
      link: {
        type: 'generated-index',
        title: 'Guides pour comprendre le MDN',
        slug: '/guides',
        keywords: ['guides']
      },
      collapsed: true,
      items: [
        'guides/la-structure-des-fichiers-markdown/index',
        'guides/le-front-matter/index',
        'guides/les-ancres-des-liens-internes/index',
        'guides/les-exemples-interactifs/index',
        'guides/les-blocs-de-codes/index',
        'guides/les-macros-et-leur-fonctionnement/index',
        'guides/les-regles-decritures-du-mdn-francophone/index'
      ],
    },
    {
      type: 'category',
      label: 'Guides pour contribuer',
      link: {
        type: 'generated-index',
        title: 'Guides pour contribuer',
        slug: '/contribuer',
        keywords: ['guides']
      },
      collapsed: true,
      items: [
        'contribuer/mettre-en-place-son-depot-bifurque/index',
        'contribuer/mettre-en-place-un-environnement-de-developpement-local/index',
        'contribuer/methodes-avancees-pour-contribuer-sur-github/index'
      ]
    },
    {
      type: 'category',
      label: 'Glossaire',
      link: {
        type: 'generated-index',
        title: 'Glossaire',
        description: 'L\'équipe francophone du MDN utilise des traductions très précises pour certains termes anglais, et pour permettre à tout le monde d\'utiliser les bons mots pour proposer des traductions conformes à notre prose, nous avons listé les mots d\'anglais ici avec la ou les traductions qui sont possibles et les contextes qui sont liés.',
        slug: '/glossaire',
        keywords: ['glossaire']
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'glossaire',
        },
      ],
      collapsed: true,
    },
  ]
}

export default sidebars
